#!/usr/bin/env bash
set -Eeuo pipefail

CONFIG_FILE="/etc/onlyoffice-email-additional-fonts.conf"
[[ -r "$CONFIG_FILE" ]] && . "$CONFIG_FILE"

FONT_DIR="${FONT_DIR:-/opt/onlyoffice-email-additional-fonts/fonts}"
STATE_DIR="${STATE_DIR:-/var/lib/onlyoffice-email-additional-fonts}"
ALIAS_FILE="${ALIAS_FILE:-/etc/onlyoffice-email-additional-fonts.aliases}"
SYNC_DOCUMENT_SERVER="${SYNC_DOCUMENT_SERVER:-auto}"
RESTART_COMMUNITY_SERVER="${RESTART_COMMUNITY_SERVER:-1}"

LOCK_FILE="/run/lock/onlyoffice-email-additional-fonts.lock"
CKROOT="/var/www/onlyoffice/WebStudio/UserControls/Common/ckeditor"
CFG="$CKROOT/config.js"
WEBROOT="$CKROOT/onlyoffice-email-additional-fonts"
WEBFONTS="$WEBROOT/fonts"
CSS="$WEBROOT/additional-fonts.css"

mkdir -p /run/lock "$STATE_DIR" "$STATE_DIR/backups" "$FONT_DIR"
exec 9>"$LOCK_FILE"
if ! flock -n 9; then
    echo "Another font update is already running; exiting."
    exit 0
fi

log() { printf '%s\n' "$*"; }
fail() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

find_container() {
    local role="$1"
    docker ps --format '{{.Names}}|{{.Image}}' | awk -F'|' -v role="$role" '
        { line=tolower($0) }
        role == "community" && (line ~ /communityserver|community-server/) { print $1; exit }
        role == "document"  && (line ~ /documentserver|document-server/)   { print $1; exit }
    '
}

COMM="$(find_container community || true)"
DOC="$(find_container document || true)"
[[ -n "$COMM" ]] || fail "ONLYOFFICE Community Server container is not running."

docker exec "$COMM" test -f "$CFG" || fail "CKEditor config not found at $CFG in $COMM"

mapfile -d '' FONT_FILES < <(find "$FONT_DIR" -type f \( -iname '*.ttf' -o -iname '*.otf' -o -iname '*.woff' -o -iname '*.woff2' \) -print0 | sort -z)
if (( ${#FONT_FILES[@]} == 0 )); then
    log "No font files found."
    log "Put .ttf, .otf, .woff or .woff2 files under:"
    log "  $FONT_DIR"
    exit 0
fi

font_family() {
    local file="$1" family=""
    if command -v fc-scan >/dev/null 2>&1; then
        family="$(fc-scan --format '%{family[0]}\n' "$file" 2>/dev/null | head -n1 || true)"
    elif [[ -n "$DOC" ]] && docker exec "$DOC" command -v fc-scan >/dev/null 2>&1; then
        local tmp="/tmp/ooeaf-$RANDOM-$(basename "$file")"
        docker cp "$file" "$DOC:$tmp" >/dev/null
        family="$(docker exec "$DOC" fc-scan --format '%{family[0]}\n' "$tmp" 2>/dev/null | head -n1 || true)"
        docker exec "$DOC" rm -f "$tmp" >/dev/null 2>&1 || true
    fi
    if [[ -z "$family" ]]; then
        family="$(basename "$file")"
        family="${family%.*}"
        family="$(printf '%s' "$family" | sed -E 's/[-_](Bold|Italic|Oblique|Regular|Medium|Light|Thin|Black|Heavy|SemiBold|Semibold|ExtraBold|ExtraLight|Book).*$//I; s/[-_]+/ /g')"
    fi
    printf '%s' "$family"
}

css_weight() {
    local n="${1,,}"
    case "$n" in
        *thin*) echo 100 ;;
        *extralight*|*ultralight*) echo 200 ;;
        *light*) echo 300 ;;
        *medium*) echo 500 ;;
        *semibold*|*demibold*) echo 600 ;;
        *extrabold*|*ultrabold*) echo 800 ;;
        *black*|*heavy*) echo 900 ;;
        *bold*) echo 700 ;;
        *) echo 400 ;;
    esac
}

css_style() {
    local n="${1,,}"
    case "$n" in
        *italic*) echo italic ;;
        *oblique*) echo oblique ;;
        *) echo normal ;;
    esac
}

STAGE="$(mktemp -d /var/tmp/onlyoffice-email-fonts.XXXXXX)"
trap 'rm -rf "$STAGE"' EXIT
mkdir -p "$STAGE/fonts"

CSS_TMP="$STAGE/additional-fonts.css"
FAMILIES_TMP="$STAGE/families.txt"
ALIASES_TMP="$STAGE/aliases.tsv"
: > "$CSS_TMP"
: > "$FAMILIES_TMP"
: > "$ALIASES_TMP"

cat >> "$CSS_TMP" <<'CSSHDR'
/* Generated by onlyoffice-email-additional-fonts. Do not edit by hand. */
CSSHDR

for src in "${FONT_FILES[@]}"; do
    base="$(basename "$src")"
    family="$(font_family "$src")"
    [[ -n "$family" ]] || continue
    cp -f "$src" "$STAGE/fonts/$base"
    printf '%s\n' "$family" >> "$FAMILIES_TMP"
    weight="$(css_weight "$base")"
    style="$(css_style "$base")"
    ext="${base##*.}"
    case "${ext,,}" in
        ttf) format=truetype ;;
        otf) format=opentype ;;
        woff) format=woff ;;
        woff2) format=woff2 ;;
        *) format=truetype ;;
    esac
    safe_family="${family//\\/\\\\}"
    safe_family="${safe_family//\"/\\\"}"
    cat >> "$CSS_TMP" <<CSS
@font-face {
  font-family: "$safe_family";
  src: url("fonts/$base") format("$format");
  font-weight: $weight;
  font-style: $style;
  font-display: swap;
}
CSS
done

sort -fu "$FAMILIES_TMP" -o "$FAMILIES_TMP"

# Optional display aliases for the CKEditor font menu.
# Format: Display Name=Real Font Family
if [[ -r "$ALIAS_FILE" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
        line="${line%%#*}"
        [[ "$line" == *=* ]] || continue
        label="${line%%=*}"
        target="${line#*=}"
        label="$(printf '%s' "$label" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
        target="$(printf '%s' "$target" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
        [[ -n "$label" && -n "$target" ]] || continue
        printf '%s\t%s\n' "$label" "$target" >> "$ALIASES_TMP"
    done < "$ALIAS_FILE"
fi
sort -fu "$ALIASES_TMP" -o "$ALIASES_TMP"

FONT_COUNT="$(find "$STAGE/fonts" -type f | wc -l)"
FAMILY_COUNT="$(wc -l < "$FAMILIES_TMP")"
ALIAS_COUNT="$(wc -l < "$ALIASES_TMP")"
MAIL_ENTRY_COUNT="$((FAMILY_COUNT + ALIAS_COUNT))"
[[ "$FONT_COUNT" -gt 0 ]] || fail "Could not stage any usable fonts."

# Build stable hashes from relative filenames and file contents only.
# Do not include the random mktemp staging path, otherwise every validation
# looks like a change and needlessly restarts Community Server.
FONT_HASH="$({
    cd "$STAGE/fonts"
    while IFS= read -r -d '' f; do
        printf '%s\0' "$f"
        sha256sum "$f" | awk '{print $1}'
    done < <(find . -type f -print0 | sort -z)
    sha256sum "$CSS_TMP" | awk '{print $1}'
    sha256sum "$FAMILIES_TMP" | awk '{print $1}'
} | sha256sum | awk '{print $1}')"

ALIAS_HASH="$(sha256sum "$ALIASES_TMP" | awk '{print $1}')"
MAIL_HASH="$(printf '%s\n%s\n' "$FONT_HASH" "$ALIAS_HASH" | sha256sum | awk '{print $1}')"
OLD_HASH="$(cat "$STATE_DIR/mail.hash" 2>/dev/null || true)"

# Always validate/repair the CKEditor patch, even when the source font set is unchanged.
docker cp "$COMM:$CFG" "$STAGE/config.js.current" >/dev/null
CFG_SHA="$(sha256sum "$STAGE/config.js.current" | awk '{print $1}')"
if ! grep -q 'ONLYOFFICE_EMAIL_ADDITIONAL_FONTS_BEGIN' "$STAGE/config.js.current"; then
    cp -f "$STAGE/config.js.current" "$STATE_DIR/backups/config.js.${CFG_SHA}.original"
fi

python3 - "$STAGE/config.js.current" "$FAMILIES_TMP" "$ALIASES_TMP" "$MAIL_HASH" <<'PY'
from pathlib import Path
import json, sys

cfg = Path(sys.argv[1])
families_path = Path(sys.argv[2])
aliases_path = Path(sys.argv[3])
cache_key = sys.argv[4][:16]
text = cfg.read_text()

START = "    /* ONLYOFFICE_EMAIL_ADDITIONAL_FONTS_BEGIN */"
END = "    /* ONLYOFFICE_EMAIL_ADDITIONAL_FONTS_END */"

if START in text and END in text:
    before, rest = text.split(START, 1)
    _, after = rest.split(END, 1)
    text = before.rstrip() + "\n" + after.lstrip("\n")

anchor = '    config.font_names = fonts.join(";");'
if anchor not in text:
    raise SystemExit("Could not find CKEditor font_names anchor")

families = [x.strip() for x in families_path.read_text().splitlines() if x.strip()]
entries = [f"{f}/{f}" for f in families]

for raw in aliases_path.read_text().splitlines():
    if not raw.strip():
        continue
    label, family = raw.split("\t", 1)
    entries.append(f"{label}/{family}")

entries = list(dict.fromkeys(entries))

block = f'''\n    /* ONLYOFFICE_EMAIL_ADDITIONAL_FONTS_BEGIN */
    var onlyofficeEmailAdditionalFonts = {json.dumps(entries, ensure_ascii=False)};
    var onlyofficeEmailFontNames = config.font_names.split(";");
    onlyofficeEmailAdditionalFonts.forEach(function(font) {{
        if (onlyofficeEmailFontNames.indexOf(font) === -1) {{
            onlyofficeEmailFontNames.push(font);
        }}
    }});
    onlyofficeEmailFontNames.sort();
    config.font_names = onlyofficeEmailFontNames.join(";");

    var onlyofficeEmailFontCss = "/UserControls/Common/ckeditor/onlyoffice-email-additional-fonts/additional-fonts.css?v={cache_key}";
    if (!config.contentsCss) {{
        config.contentsCss = [];
    }} else if (typeof config.contentsCss === "string") {{
        config.contentsCss = [config.contentsCss];
    }}
    config.contentsCss = config.contentsCss.filter(function(css) {{
        return css.indexOf("/UserControls/Common/ckeditor/onlyoffice-email-additional-fonts/additional-fonts.css") === -1;
    }});
    config.contentsCss.push(onlyofficeEmailFontCss);
    /* ONLYOFFICE_EMAIL_ADDITIONAL_FONTS_END */\n'''

text = text.replace(anchor, anchor + block, 1)
cfg.write_text(text)
PY

NEW_CFG_HASH="$(sha256sum "$STAGE/config.js.current" | awk '{print $1}')"
CURRENT_CFG_HASH="$(docker exec "$COMM" sha256sum "$CFG" | awk '{print $1}')"
PATCH_CHANGED=0
if [[ "$NEW_CFG_HASH" != "$CURRENT_CFG_HASH" ]]; then
    docker cp "$STAGE/config.js.current" "$COMM:$CFG" >/dev/null
    PATCH_CHANGED=1
fi

FILES_CHANGED=0
EXISTING_WEB_COUNT="$(docker exec "$COMM" sh -lc "find '$WEBFONTS' -maxdepth 1 -type f 2>/dev/null | wc -l" 2>/dev/null || echo 0)"
if [[ "$MAIL_HASH" != "$OLD_HASH" ]] || ! docker exec "$COMM" test -f "$CSS" || [[ "$EXISTING_WEB_COUNT" -ne "$FONT_COUNT" ]]; then
    docker exec "$COMM" rm -rf "$WEBROOT"
    docker exec "$COMM" mkdir -p "$WEBFONTS"
    docker cp "$STAGE/fonts/." "$COMM:$WEBFONTS/" >/dev/null
    docker cp "$CSS_TMP" "$COMM:$CSS" >/dev/null
    FILES_CHANGED=1
fi

docker exec "$COMM" chown -R onlyoffice:onlyoffice "$WEBROOT" "$CFG"
docker exec "$COMM" chmod -R a+rX "$WEBROOT"
docker exec "$COMM" chmod 0644 "$CFG" "$CSS"

# Verify the exact files the browser/editor needs.
docker exec "$COMM" grep -q 'ONLYOFFICE_EMAIL_ADDITIONAL_FONTS_BEGIN' "$CFG" || fail "CKEditor patch marker missing after update"
docker exec "$COMM" test -s "$CSS" || fail "Generated webfont CSS is missing"
REMOTE_COUNT="$(docker exec "$COMM" find "$WEBFONTS" -maxdepth 1 -type f | wc -l)"
[[ "$REMOTE_COUNT" -eq "$FONT_COUNT" ]] || fail "Expected $FONT_COUNT webfont files, found $REMOTE_COUNT"

if [[ "$PATCH_CHANGED" -eq 1 || "$FILES_CHANGED" -eq 1 ]]; then
    printf '%s\n' "$MAIL_HASH" > "$STATE_DIR/mail.hash"
    if [[ "$RESTART_COMMUNITY_SERVER" == "1" ]]; then
        log "Restarting Community Server to ensure the Mail editor reloads the updated CKEditor config..."
        docker restart --timeout 30 "$COMM" >/dev/null
    fi
fi

sync_docs=0
case "${SYNC_DOCUMENT_SERVER,,}" in
    1|yes|true|on) sync_docs=1 ;;
    auto) [[ -n "$DOC" ]] && sync_docs=1 ;;
    *) sync_docs=0 ;;
esac

if [[ "$sync_docs" -eq 1 && -n "$DOC" ]]; then
    DOC_HASH_FILE="$STATE_DIR/document.hash"
    DOC_OLD_HASH="$(cat "$DOC_HASH_FILE" 2>/dev/null || true)"
    DOC_DEST="/usr/share/fonts/truetype/custom/onlyoffice-email-additional-fonts"
    DOC_EXISTING_COUNT="$(docker exec "$DOC" sh -lc "find '$DOC_DEST' -maxdepth 1 -type f 2>/dev/null | wc -l" 2>/dev/null || echo 0)"
    if [[ "$FONT_HASH" != "$DOC_OLD_HASH" || "$DOC_EXISTING_COUNT" -ne "$FONT_COUNT" ]]; then
        docker exec "$DOC" rm -rf "$DOC_DEST"
        docker exec "$DOC" mkdir -p "$DOC_DEST"
        docker cp "$STAGE/fonts/." "$DOC:$DOC_DEST/" >/dev/null
        docker exec "$DOC" fc-cache -f >/dev/null 2>&1 || true
        if docker exec "$DOC" test -x /usr/bin/documentserver-generate-allfonts.sh; then
            log "Regenerating ONLYOFFICE Document Server font catalogue..."
            docker exec "$DOC" /usr/bin/documentserver-generate-allfonts.sh >/dev/null
        fi
        printf '%s\n' "$FONT_HASH" > "$DOC_HASH_FILE"
    fi
fi

log ""
log "ONLYOFFICE additional fonts are current."
log "Font source directory: $FONT_DIR"
log "Font files installed: $FONT_COUNT"
log "Real font families found: $FAMILY_COUNT"
log "Mail aliases configured: $ALIAS_COUNT"
log "Mail font entries exposed: $MAIL_ENTRY_COUNT"
log "Community Server: $COMM"
if [[ -n "$DOC" ]]; then log "Document Server: $DOC (sync: $SYNC_DOCUMENT_SERVER)"; fi
log ""
log "If Mail is already open in a browser, reload the whole ONLYOFFICE page before opening a new compose window."
